# Generated by Django 2.1.4 on 2018-12-16 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0003_auto_20181216_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('holder', 'email')},
        ),
    ]
